"""empty message

Revision ID: 462478f2ef1a
Revises: ae06e83a2fa2
Create Date: 2022-08-19 01:17:51.539436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462478f2ef1a'
down_revision = 'ae06e83a2fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=250), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
