"""empty message

Revision ID: 7b68e448addc
Revises: 51006d02caa5
Create Date: 2022-08-19 00:40:23.063741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b68e448addc'
down_revision = '51006d02caa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_character')
    op.add_column('character', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'character', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.drop_column('character', 'user_id')
    op.create_table('fav_character',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='fav_character_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fav_character_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
